routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Telegram\Bot\Laravel\Facades\Telegram;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/clear-cache', function() {
    Artisan::call('cache:clear');
    Artisan::call('config:cache');
});

Route::middleware(['auth'])->prefix('admin')->namespace('Settings')->name('admin.')->group(function (){
    Route::get('/', 'DashboardController@index')->name('index');

    Route::get('/setting', 'SettingController@index')->name('setting.index');
    Route::post('/setting/store', 'SettingController@store')->name('setting.store');

    Route::post('setting/setwebhook', 'SettingController@setwebhook')->name('setting.setwebhook');
    Route::post('setting/getwebhookinfo', 'SettingController@getwebhookinfo')->name('setting.getwebhookinfo');
});

Route::post(Telegram::getAccessToken(), function(){
    app('App\Http\Controllers\Telegram\TelegramController')->webhook();
})->middleware('tgauth');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/backend/index.blade.php
@extends('backend.layouts.app')

@section('content')

    <div class="container">
        <h1>BackEnd</h1>
    </div>

@endsection

resources/views/backend/setting.blade.php
@extends('backend.layouts.app')

@section('content')

    <div class="container">

        @if(Session::has('status'))
            <div class="alert alert-info">
                <span>
                    {{ Session::get('status') }}
                </span>
            </div>
        @endif
        <form action="{{route('admin.setting.store')}}" method="post">
            {{csrf_field()}}
            <div class="form-group">
                <label >Url callback для Telegrambot</label>
                <div class="input-group">
                    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Действие
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="#" onclick="document.getElementById('url_callback_bot').value = '{{url('')}}'">
                                Вставить url
                            </a>
                        </li>
                        <li>
                            <a href="#" onclick="event.preventDefault(); document.getElementById('setwebhook').submit();">
                                Отправить url
                            </a>
                        </li>
                        <li>
                            <a href="#" onclick="event.preventDefault(); document.getElementById('getwebhookinfo').submit();">
                                Получить информацию
                            </a>
                        </li>
                    </ul>
                </div>
                <input type="url" class="form-control" id="url_callback_bot" name="url_callback_bot" value="{{$url_callback_bot ?? ''}}">
            </div>
            <button class="btn btn-primary" type="submit">Сохранить</button>
        </form>

            <form id="setwebhook" action="{{ route('admin.setting.setwebhook')  }}" method="POST" style="display: none">
                {{csrf_field()}}
                <input type="hidden" name="url" value="{{$url_callback_bot ?? ''}}">
            </form>

            <form id="getwebhookinfo" action="{{ route('admin.setting.getwebhookinfo')  }}" method="POST" style="display: none">
                {{csrf_field()}}
            </form>
    </div>

@endsection